### ISSUE TITLE
Background for brands

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#10]
we need the "background_image" added to the brands in the location call.
Should exist within the brand object meaning there will be server side code to generate these.

**Comment by coho1988** [comment]
put in blob.json

**Comment by jpdemiranda** [comment]
Looks like this is good now
https://bonapp.blob.core.windows.net/configs/bamco.json
`{
"language": "en",
"locations": [
{
"name": "Emeryville",
"logo": "https://bonapp.blob.core.windows.net/logos/grifols.jpg",
"theme_color": "003798",
"alt_color": "FFFFFF",
"menu": [
{
"display": "News & Events",
"url": "http://emeryville.cafebonappetit.com/event"
},
{
"display": "Wellness",
"url": "http://emeryville.cafebonappetit.com/wellness"
},
{
"display": "Catering",
"url": "http://emeryville.cafebonappetit.com/catering"
},
{
"display": "Contact Us",
"url": "http://emeryville.cafebonappetit.com/#panel-tell-us-what-you-think-4"
}
],
"id": "616kLAy0KgFZvRNk",
"dietary_preferences": [
{
"id": "vegan",
"label": "Vegan",
"description": "Vegan: Contains absolutely no animal or dairy products.",
"image": "http://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-668e3c.png?v=1470070467",
"is_filter": true
},
{
"id": "vegetarian",
"label": "Vegetarian",
"description": "Vegetarian: Contains no meat, fish, poultry, shellfish or products derived from these sources but may contain dairy or eggs",
"image": "http://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-c9d18b.png?v=1470070467",
"is_filter": true
},
{
"id": "seafood_watch",
"label": "Seafood Watch",
"description": "Seafood Watch: Contains seafood that meets the Monterey Bay Aquarium&#039;s Seafood Watch guidelines for commercial buyers.",
"image": "http://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-43c4b7.png?v=1470070468",
"is_filter": false
},
{
"id": "farm_to_fork",
"label": "Farm to Fork",
"description": "Farm to Fork: Contains seasonal, minimally processed ingredients from a local farm, ranch, or fishing boat.",
"image": "http://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-d58f59.png?v=1491523150",
"is_filter": false
},
{
"id": "in_balance",
"label": "In Balance",
"description": "In Balance: Contains a balanced portion of whole grains, fresh fruits and vegetables, and lean protein with a minimum amount of healthy fat",
"image": "http://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-inbalance.png?v=1470070460",
"is_filter": true
},
{
"id": "organic",
"label": "Organic",
"description": "Organic: Contains at least 95 percent organically produced ingredients (by weight) from a USDA certified source",
"image": "http://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-e6674a.png?v=1470070465",
"is_filter": false
},
{
"id": "no_gluten_ingredients",
"label": "Made without Gluten- Containing Ingredients",
"description": "Made without Gluten-Containing Ingredients: Due to our open kitchens that handle gluten, we cannot guarantee that items made without gluten-containing ingredients are �gluten-free,� as defined by the FDA.  We make every effort to avoid gluten cross-contact; however there is always the potential for cross-contact with other gluten-containing food items, particularly in our self-serve facilities. We encourage guests to speak to the chef or manager regarding any questions about ingredients.",
"image": "http://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-ce9d00.png?v=1470070466",
"is_filter": true
},
{
"id": "halal",
"label": "Halal",
"description": "Halal: Contains meat prepared in accordance with Muslim dietary law",
"image": "http://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-48b8d2.png?v=1470070468",
"is_filter": false
},
{
"id": "kosher",
"label": "Kosher",
"description": "Kosher: Contains only ingredients prepared in accordance with Jewish Dietary Law",
"image": "http://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-5998c9.png?v=1470070467",
"is_filter": false
},
{
"id": "humane",
"label": "Humane",
"description": "Humane: Contains humanely raised meat, poultry, or eggs. Must be certified by a credible third-party animal welfare organization.\n",
"image": "http://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-ebce7b.png?v=1483484130",
"is_filter": false
},
{
"id": "locally_crafted",
"label": "Locally Crafted",
"description": "Locally Crafted: Contains products crafted by a small, locally\nowned food business using socially and/or\nenvironmentally responsible practices.",
"image": "http://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-locally-crafted.png?v=1470070449",
"is_filter": false
}
],
"brands": [
{
"id": "B5XY4Aq2ljsd4PYAQp70HB92M8jO0v",
"background_image_android": "https://bonapp.blob.core.windows.net/images/final-b1-1440w.png",
"background_image_ios": "https://bonapp.blob.core.windows.net/images/final-b1-1442w.png",
"brand_location_description": "Building E, Ground Floor"
}
]
}
]
}`
